// Clean Data
MATCH (n:DayClose) WITH n LIMIT 50000 DETACH DELETE n;
MATCH (n:DayClose) WITH n LIMIT 50000 DETACH DELETE n;
MATCH (n) WITH n LIMIT 10000 DETACH DELETE n;

// Remove Constraints
DROP CONSTRAINT Customer_Id IF EXISTS;
DROP CONSTRAINT Stock_ticker IF EXISTS;
DROP CONSTRAINT Fund_ticker IF EXISTS;
DROP CONSTRAINT Day_date IF EXISTS;
DROP CONSTRAINT DayClose_id IF EXISTS;
